services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hydra"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./hydra/init-db.sql:/docker-entrypoint-initdb.d/hydra.sql:ro
      - ./kratos/init-db.sql:/docker-entrypoint-initdb.d/kratos.sql:ro
      - ./postgres/data:/var/lib/postgresql/data

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    command: migrate sql -e --yes
    environment:
      DSN: postgres://hydra:secret@db:5432/hydra?sslmode=disable
    restart: on-failure

  hydra:
    image: oryd/hydra:v2.2.0
    command: serve -c /etc/config/hydra/hydra.yml all
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
    environment:
      DEV: true
      DSN: postgres://hydra:secret@db:5432/hydra?sslmode=disable
      LOG_LEVEL: trace
      OAUTH2_EXPOSE_INTERNAL_ERRORS: true
      SECRETS_SYSTEM: insecure-secret0 # This should be a secure random value
    ports:
      - 4444:4444 # Public port
      - 4445:4445 # Admin port
      - 5555:5555 # Port for hydra token user
    restart: unless-stopped
    volumes:
      - ./hydra/hydra.yml:/etc/config/hydra/hydra.yml:ro

  kratos-migrate:
    image: oryd/kratos:v1.1.0
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    environment:
      DSN: postgres://kratos:secret@db:5432/kratos?sslmode=disable
    restart: on-failure
    volumes:
      - ./kratos/kratos.yml:/etc/config/kratos/kratos.yml:ro

  kratos:
    image: oryd/kratos:v1.1.0
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    environment:
      DSN: postgres://kratos:secret@db:5432/kratos?sslmode=disable
      LOG_LEVEL: trace
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    restart: unless-stopped
    volumes:
      - ./kratos/identity.schema.json:/etc/config/kratos/identity.schema.json:ro
      - ./kratos/kratos.yml:/etc/config/kratos/kratos.yml:ro

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    environment:
      COOKIE_SECRET: insecure-secret0 # This should be a secure random value
      CSRF_COOKIE_NAME: cookie_name
      CSRF_COOKIE_SECRET: changeme
      HYDRA_ADMIN_URL: http://hydra:4445
      DANGEROUSLY_DISABLE_SECURE_CSRF_COOKIES: true
      KRATOS_BROWSER_URL: http://127.0.0.1:4433
      KRATOS_PUBLIC_URL: http://kratos:4433
      PORT: 4455
    ports:
      - 4455:4455
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
