version: "3.7"

services:

  hydra:
    image: oryd/hydra:v1.9.2
    depends_on:
      - hydra-migrate
    environment:
      DSN: postgres://hydra:secret@db:5432/hydra?sslmode=disable
      SECRETS_SYSTEM: insecure-secret0 # This should be a secure random value
      URLS_CONSENT: http://localhost:9020/consent
      URLS_LOGIN: http://localhost:9020/login
      URLS_SELF_ISSUER: https://localhost:9000/
    ports:
      - 9000:4444
      - 9001:4445
    restart: unless-stopped

  hydra-migrate:
    image: oryd/hydra:v1.9.2
    command:
      ["migrate", "sql", "--yes", "postgres://hydra:secret@db:5432/hydra?sslmode=disable"]
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: hydra
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: hydra
    ports:
      - 5432:5432

  hydra-oauth-example:
    image: oryd/hydra-login-consent-node:v1.3.2
    depends_on:
      - hydra
    environment:
      HYDRA_ADMIN_URL: https://hydra:4445
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - 9020:3000
    restart: unless-stopped

  kratos-migrate:
    image: oryd/kratos:v0.5.5
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    environment:
      - DSN=postgres://hydra:secret@db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure
    volumes:
      - ./kratos/kratos.yml:/etc/config/kratos/kratos.yml:ro

  kratos:
    image: oryd/kratos:v0.5.5
    command: serve -c /etc/config/kratos/kratos.yml --dev
    depends_on:
      - kratos-migrate
    environment:
      - DSN=postgres://hydra:secret@db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    volumes:
      - ./kratos/:/etc/config/kratos/:ro

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.5.0-alpha.1
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - PORT=4455
      - SECURITY_MODE=
    ports:
      - "4455:4455"
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
